n: 3

psi_wall:     [0.3, 0.35, 0.4]
q:            [Qfactors.Unity(), Qfactors.Unity(), Qfactors.Unity()]
B:            [[0,1,0], [0,1,0], [0,1,0]]
Efield:       [Electric_fields.Radial(psi_wall, q), Electric_fields.Radial(psi_wall, q), Electric_fields.Radial(psi_wall, q)]

species:      ["e", "e", "e"] 
mu:           [10**(-5), 10**(-5), 10**(-5)]
theta0:       [0, 0, 0]
psi0:         [0.03, 0.04, 0.05]
z0:           [0, 0, 0]
Pz0:          [-0.04, -0.04, -0.04]
tspan:        [np.linspace(0,10000, 1000), np.linspace(0,10000, 1000), np.linspace(0,10000, 1000)]
