n: 3

psi_wall: [0.12, 0.12, 0.12]
q: ["Qfactors.Unity()"]
B: [[0, 1, 1], [0, 1, 1], [0, 1, 1]]
Efield: ["Electric_fields.Nofield()"]

species: ["e"]
mu: ["10**(-5)"]
theta0: [0, 0, 0]
psi0: [0.03, 0.04, 0.05]
z0: [0, 0, 0]
Pz0: [-0.0272, -0.0272, -0.0272]
tspan: ["np.linspace(0,10000, 10000)"]
